package main

import (
	"flag"
	"fmt"
	"html/template"
	"net/http"
	"toolset/caseviewer/caseobj"
)

func caseHandler(emrcase *caseviewer.PatientCase, temp *template.Template) func(http.ResponseWriter, *http.Request) {
	return func(w http.ResponseWriter, r *http.Request) {
		if err := temp.Execute(w, emrcase); err != nil {
			fmt.Println(err)
		}
	}
}

func main() {
	jsonFile := flag.String("i", "", "The json file generated by localdriver.py")
	templateFile := flag.String("t", "", "The HTML template file")
	port := flag.String("p", "29000", "the test viewer port")
	flag.Parse()

	patientCase := &caseviewer.PatientCase{}
	patientCase.Load(*jsonFile)
	funcMap := template.FuncMap{
		"noescape": func(s string) template.HTML {
			return template.HTML(s)
		},
	}

	t, err := template.New("case.html").Funcs(funcMap).ParseFiles(*templateFile)
	if err != nil {
		fmt.Println(*templateFile, err)
		return
	}

	handler := caseHandler(patientCase, t)
	http.HandleFunc("/", handler)
	http.ListenAndServe(":"+*port, nil)
}
